# Generated by Django 4.2.3 on 2023-07-07 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='url_img',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='users_watchlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
