# Generated by Django 4.2.3 on 2023-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_listings_highest_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='url_img',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
